# Generated by Django 5.0.6 on 2024-06-21 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetosBd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos/')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('React', 'React'), ('Golang', 'Golang'), ('JavaScript', 'JavaScript')], max_length=100)),
                ('nota', models.IntegerField()),
                ('data_postagem', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
