# Generated by Django 5.0.6 on 2024-06-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitePortifolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadosBd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos_certificado')),
                ('categoria', models.CharField(choices=[('Programação', 'Programação'), ('Front-end', 'Front-end'), ('Ux-designer', 'Ux-designer'), ('Devops', 'Devops')], max_length=100)),
            ],
        ),
    ]
