# Generated by Django 5.0.6 on 2024-06-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitePortifolio', '0002_certificadosbd'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetosbd',
            name='linkgit',
            field=models.CharField(default='qualquercoisa', max_length=100),
        ),
        migrations.AddField(
            model_name='projetosbd',
            name='linksite',
            field=models.CharField(default='qualquercoisa', max_length=100),
        ),
    ]
