# Generated by Django 5.0.6 on 2024-06-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitePortifolio', '0003_projetosbd_linkgit_projetosbd_linksite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadosbd',
            name='categoria',
            field=models.CharField(choices=[('Programação', 'Programação'), ('Front-end', 'Front-end'), ('Ux-designer', 'Ux-designer'), ('Devops', 'Devops'), ('Banco-de-dados', 'Banco de dados')], max_length=100),
        ),
    ]
