# Generated by Django 5.2 on 2025-06-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitePortifolio', '0004_alter_certificadosbd_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificadosbd',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='projetosbd',
            name='imagem',
        ),
        migrations.AddField(
            model_name='certificadosbd',
            name='imagem_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL da imagem (Imgur)'),
        ),
        migrations.AddField(
            model_name='projetosbd',
            name='imagem_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL da imagem (Imgur)'),
        ),
        migrations.AlterField(
            model_name='certificadosbd',
            name='categoria',
            field=models.CharField(choices=[('Programação', 'Programação'), ('Front-end', 'Front-end'), ('Ux-designer', 'Ux-designer'), ('Devops', 'Devops'), ('Banco-de-dados', 'Banco de dados'), ('CyberSegurity', 'CyberSegurity'), ('Mobile', 'Mobile')], max_length=100),
        ),
        migrations.AlterField(
            model_name='projetosbd',
            name='tipo',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('React', 'React'), ('Golang', 'Golang'), ('C#', 'C#'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('Flutter', 'Flutter')], max_length=100),
        ),
    ]
